version: '3'

services:
  reviews:
    build: ./
    command: sh -c 'npm install; npm run seed; npm start' 
    depends_on:
      - 'database'
    ports: 
      - '3003:3003'

  database:
    image: mongo:latest

